import './globals.css'
import type { Metadata } from 'next'
import { Bakbak_One } from 'next/font/google'
import FlowField from '@/components/FlowField'
//const inter = Inter({ subsets: ['latin'] })
const bakbak = Bakbak_One({weight: '400', subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bakbak.className}>
        <FlowField className='absolute top-0 left-0 -z-10 w-screen min-h-screen overflow-hidden' />
        {children}
      </body>
    </html>
  )
}
